version: '3'

services: 
  web:
    build: ./web
    ports:
      - 80:80

  api:
    build: ./api
    ports: 
      - 8080:8080
    environment: 
      DB_URL: mongodb://db/monemu

  db:
    image: mongo:4.0-xenial
    ports: 
      - 27017:27017
    volumes:
      - monemu:/data/db

volumes:
  monemu: